# Generated by Django 3.2.12 on 2022-02-07 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(null=True)),
                ('by', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('text', models.CharField(max_length=200, null=True)),
                ('dead', models.BooleanField(null=True)),
                ('parent', models.IntegerField(null=True)),
                ('poll', models.IntegerField(null=True)),
                ('kids', models.IntegerField(null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('score', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('parts', models.IntegerField(null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.type')),
            ],
        ),
    ]
